services:
  - docker

jobs:
  include:
    # Execute java unit- and integration tests
    - stage: test
      language: java
      jdk:
        - oraclejdk8
      script: mvn -DcompilerArgument=-Xlint:unchecked test -P all-unit-tests
      after_success: mvn jacoco:report coveralls:report

    # Execute Cypress for UI testing
    # see https://docs.cypress.io/guides/guides/continuous-integration.html
    - stage: test
      language: node_js
      node_js:
        - "10"
      addons:
        apt:
          packages:
            # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
            - libgconf-2-4
      cache:
        # Caches $HOME/.npm when npm ci is default script command
        # Caches node_modules in all other cases
        npm: true
        directories:
          # we also need to cache folder with Cypress binary
          - ~/.cache
      before_script:
        - cd tests
        # run docker-aio
        - run_docker_dataverse.sh
      install:
        - npm ci
      script:
        - $(npm bin)/cypress run --record
